<?php

/**
 * @file
 * Installs demo content.
 */

/**
 * Implements hook_modules_installed().
 */
function jigs_demo_content_modules_installed($modules) {
  if (!in_array('jigs_demo_content', $modules)) {
    return;
  }

  $home_uuid = 'ff690241-146d-4a2c-b107-28529f746008';

  /** @var \Drupal\node\Entity\Node $node */
  $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
    'uuid' => $home_uuid,
  ]);
  $node = reset($nodes);

  if ($node) {
    $config = \Drupal::service('config.factory')->getEditable('system.site');
    $config->set('page.front', '/node/' . $node->id());
    $config->save();

    \Drupal::logger('jigs_demo_content')->info('Homepage set to /node/' . $node->id());
  }
  else {
    \Drupal::logger('jigs_demo_content')->error('Unable to set homepage');
  }
}
